### ISSUE TITLE
Suggestions for Vedui's Community Server Modlet for A17.x

### ISSUE THREAD

**Issue by Satissis** [Satissis/7D2D_Modlets#2]
This is a topic to add suggestions for changes to the core items ingame, so if you have any suggestions, post them here.

If we decide to add the changes, I'll add them to the todo list.

## Todo list
- [ ] Better power vs gas usage of generators/banks
- [ ] More Doors
- [ ] More Lights
- [ ] More build able astatic objects
- [ ] New colors for our paint jobs. (_Will properly see if I can get all the old once back again_)
- [ ] Temp immune to bleeds after using first aids (way to easy to bleed in this game)
- [ ] Make perk book buffs last longer.

## Stuff to check
- [ ] Make certain of the stuff pick-upable or wrenchable
- [ ] A extra row in the backpack (_Will have to check if it's possible without editing the dll file_)
- [ ] Powered doors/drawbridges (_Will have to test if that's possible_)
- [ ] Add cola to the game. (_Check if there is an asset we can use for this_)

**Comment by Trollseatkittens** [comment]
a extra row in the backpack
better power vs gas useage of generators/banks
new cars w/more passengers (maybe even able to shoot from it?)
fewer bloodmoons overall but more dangerous/harder/worth doing
fishing <3 and better one then wotw had cuz its to broken
fix the water mechanic plz so it dosnt make weird holes in surface (wait back to topic)
new boss zombie thats actually tough to bring down on your own
new animals /replace vulture with crows?
other quests then the trader ones /new npc perhaps somewhere /to craft or kill certain amount
better looking windows
more doors
powered doors/drawbridges
turret replacement that just uses rocks so we dont waste ammo on it /for comn base not for horde base ofc 
new zombie skins
new armours ( we look like clones :P)
new colours for our paint jobs
better charecter creation
add cola to the game (i dont drink coffee :P)
temp immune to bleeds after using first aids (way to easy to bleed in this game)
get TNT back so we can use it for clearing out areas/buildings we dont like insteed of waste 6 hours digging/chopping it down
better looking stripper zombie (im tired of her she dosnt do it for me..i like em pale and white hair plz)
oki running out of ideas for now 
thank you 
"Every brain looks the same after a .50 Caliber hits" - Trolls 2019

**Comment by Satissis** [comment]
### Vedui's comment on Discord:

>For perk books.. Interesting idea. What I would prefer tho, is that skill learnings (like the current ones you find) should last longer. Let it be say 7 days. Right now you find something, but I go "Hmm, do I really need this in the next hour? no.. so let's save" ..and then you're back home and put it in your bookcase never to re-use. I mostly sell them.
If they had say 7 day (or 7 hour in game) buff time, then I could go "Sure I might not farm in the next hour, but I will in the next couple or three days, so I might as well read this farming book"

> one thing to consider might be to make certain of the stuff pick-upable or wrenchable .. ie, when broken it drops the item, such as the hospital beds, and the like. Things you see around and wanna pick up (destroy might be better tho, to avoid the "e to pick up" on everything), so you could go to hospital and "wrench" a body bag and get it, for instance. Not sure how that'd be done, if you can separate wrenching from destroying


@Trollseatkittens I updated first post and added those I believe might be possible to do with my current knowledge of 7d2d modding ;)
